In [1]:
a = [1,2,3,4]
b = [2,3,4,5]

In [3]:
ab = []

for i in range(0, len(a)):
    ab.append(a[i]*b[i])

ab

[2, 6, 12, 20]

In [11]:
import numpy as np

In [13]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [14]:
a*b

array([ 2,  6, 12, 20])

In [17]:
arr = np.array([4,5,6,7])

In [18]:
type(arr)

numpy.ndarray

In [19]:
np.array([3.14, 5, 6, 7])

array([3.14, 5.  , 6.  , 7.  ])

In [20]:
np.array([3.14, 5, 6, 7], dtype = "int")

array([3, 5, 6, 7])

In [21]:
# sıfırlardan array oluşturma
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

np.full((3,5), 3)

In [26]:
#0'dan(dahil) 31'e kadar(dahil değil) 3'er 3'er artacak şekilde bir dizi oluşur
np.arange(0, 31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [29]:
#0 ile bir arasında 10 tane değer oluşturur.(0 ve 1 dahil.)
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
#ortalaması 10, standart sapması 4, 3'e 4'lük bir array
np.random.normal(10, 4, (3,4))

array([[ 7.00151853, 11.91176463,  9.82294043, 15.65399436],
       [ 4.27670769,  8.00320657,  4.77127703,  1.77329141],
       [ 8.02292253, 12.58692562, 11.10670574,  3.18166538]])

In [32]:
np.random.randint(0, 10, (3,3))

array([[8, 6, 5],
       [6, 1, 1],
       [6, 0, 8]])

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [42]:
b = np.random.randint(10, size = (3,5))
b

array([[0, 5, 2, 7, 3],
       [8, 1, 2, 4, 2],
       [1, 2, 4, 6, 3]])

In [38]:
b.ndim

2

In [40]:
b.shape

(3, 5)

In [41]:
b.size

15

In [43]:
b.dtype

dtype('int32')

In [44]:
c = np.arange(1, 10)
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
d = c.reshape(3, 3)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
d.ndim

2

# Array Birleştirme (Concatenation)

In [57]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
arr3 = np.array([9, 10, 11, 12])

In [58]:
arr4 = np.concatenate([arr1, arr2, arr3])
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
#iki boyut

In [61]:
arr5 = np.array([[1,2,3],
                [4,5,6]])

In [67]:
np.concatenate([arr5,arr5])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

# Array Ayırma (Splitting)

In [70]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [74]:
a, b, c = np.split(x, [3, 5])
a

array([1, 2, 3])

In [75]:
b

array([99, 99])

In [76]:
c

array([3, 2, 1])

In [77]:
# iki boyutlu ayırma

In [88]:
y = np.arange(16).reshape(4,4)
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [94]:
ust, alt = np.vsplit(y, [2])

In [92]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [93]:
alt 

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [95]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [99]:
np.hsplit(y, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [101]:
sag, sol = np.hsplit(y, [2])

In [102]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [103]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sıralama(Sorting)

In [104]:
v = np.array([5, 2, 12, 6, 90, 76, 1])

In [109]:
np.sort(v)

array([ 1,  2,  5,  6, 12, 76, 90])

In [110]:
# iki boyutlu sıralama

In [112]:
g = np.random.normal(20 ,5, (3, 3))

In [113]:
g

array([[23.13810028, 19.57743879, 21.33869356],
       [21.05967478, 12.60666622, 21.66841393],
       [15.44210122, 12.65243614, 24.45776933]])

In [115]:
#satırları sıralar
np.sort(g, axis = 1)

array([[19.57743879, 21.33869356, 23.13810028],
       [12.60666622, 21.05967478, 21.66841393],
       [12.65243614, 15.44210122, 24.45776933]])

In [116]:
# sütunları sıralar
np.sort(g, axis = 0)

array([[15.44210122, 12.60666622, 21.33869356],
       [21.05967478, 12.65243614, 21.66841393],
       [23.13810028, 19.57743879, 24.45776933]])

# Index

In [118]:
k = np.random.randint(10, size = 10)
k

array([8, 2, 4, 3, 1, 2, 1, 3, 4, 0])

In [119]:
k[0]

8

In [120]:
k[-1]

0

In [121]:
k[3]

3

In [122]:
k[3] = 5

In [125]:
f = np.arange(16).reshape(4,4)
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [126]:
f[1, 1]

5

In [129]:
f[3, 1] = 5.6

In [131]:
f #ondalıklı yapamadık çünkü başta array integer değerlerden oluştuğu için otomatikmen ondalık sayıyı tam sayıya çevirdi

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  5, 14, 15]])

# Slicing ile Elemanlara Erişmek (Array Alt kümesine erişmek)

In [133]:
a = np.arange(20, 30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [134]:
a[0:3]

array([20, 21, 22])

In [135]:
a[:3]

array([20, 21, 22])

In [136]:
a[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [137]:
a[1::2]

array([21, 23, 25, 27, 29])

In [138]:
a[0::3]

array([20, 23, 26, 29])

In [139]:
# iki boyutlu slice işlemleri

In [142]:
b = np.random.randint(10, size = (5,5))
b

array([[2, 1, 9, 3, 6],
       [7, 8, 7, 6, 9],
       [0, 4, 2, 2, 1],
       [1, 9, 8, 8, 5],
       [2, 8, 9, 2, 5]])

In [144]:
b[:,0]

array([2, 7, 0, 1, 2])

In [145]:
b[:,:]

array([[2, 1, 9, 3, 6],
       [7, 8, 7, 6, 9],
       [0, 4, 2, 2, 1],
       [1, 9, 8, 8, 5],
       [2, 8, 9, 2, 5]])

In [146]:
b[:, 1]

array([1, 8, 4, 9, 8])

In [147]:
b[0,:]

array([2, 1, 9, 3, 6])

In [149]:
b[0:2, 0:3]

array([[2, 1, 9],
       [7, 8, 7]])

In [151]:
b[::, :2]

array([[2, 1],
       [7, 8],
       [0, 4],
       [1, 9],
       [2, 8]])

In [152]:
b[1:3, 0:2]

array([[7, 8],
       [0, 4]])

# NumPy ile iki bilinmeyenli denklem çözümü

5*x0 + x1 = 12 

x0 + 3*x1 = 10

In [154]:
a = np.array([[5, 1], [1,3]])
b = np.array([12, 10])

In [155]:
x = np.linalg.solve(a,b)

In [156]:
x

array([1.85714286, 2.71428571])